server:
  port: 8080

spring:
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:mem:usersdb
    driver: org.h2.Driver
    username: test
    password: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

application:
  security:
    jwt:
      secret-key: 482B4D6251655468576D5A7134743677397A24432646294A404E635266556A58
      expiration: 60000 # 1 minuto